apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raspi-monitor
spec:
  selector:
    matchLabels:
      app: raspi-monitor 
  template:
    metadata:
      labels:
        app: raspi-monitor # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: raspi-monitor
          image: brendanrobert1/raspi-monitoring:0.0.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName